### ISSUE TITLE
Sometimes a Sub/End Sub block will produce 'Assertion `!currently_naked' failed.' errors for no obvious reason.

### ISSUE THREAD

**Issue by supercom32** [uli/dragonbasic#9]
Issue found using the latest version of Dragon Basic under Linux (Commit ID: d2ce042366068083a5fe3089873a22221fffbc26)

Sometimes a Sub/End Sub will produce the error 'mf: MF.cpp:3688: void Parser::parseAll(): Assertion `!currently_naked' failed.' with no obvious reason why. In such cases the methods affected are not empty, so there is no clear indication as to why this is happening. It might be possible to find a simple reduced test case to demonstrate this, but I haven't found one yet. It seems to be rather arbitrary when it happens. Probably easier to figure out what triggers 'Assertion `!currently_naked' failed.' in MF, and then try figure out what corner edge-case would trigger this assertion when a Sub/Function clearly has code in it.

Workaround: Adding a "Log" statement to the top of the method seems to resolve this issue. Might be connected with the empty Sub/End Sub issue in some way. I assume the "Log" statement somehow indicates to MF that the method is not empty?

Note: Because of the arbitrary and randomness of this issue, this is probably more serious than others logged.  Because I have yet to find a predictable reason for this problem, the only recourse a user has is to insert "Log" statements anytime it happens. If I find a small code test-case that can reproduce this issue, I'll add a comment to this issue.

**Comment by uli** [comment]
This was a bit tricky...

A "naked" function is a routine without prolog and epilog. If a routine does not call any other routines, it does not have to save registers, so we omit that if possible. This is done either manually (for TIN code), or by DBC (for BASIC code), meaning that DBC needs to know if any of the things it does will turn out to be implemented as a function call. This is obviously hairy, and what bit you there is that some operators
(namely "=", "<>" and "F/") are not inlined, which is something DBC is not aware of. So if you use any of these operators, but do not call any other functions from BASIC, the code is erroneously declared "naked", and MF complains when it notices that.

The commit above should fix this.

**Comment by uli** [comment]
Test case for reference:

#include <core.dbc>
DIM a,b
sub foo
	a = a <> b
end sub
start:

**Comment by supercom32** [comment]
Hey Uli,

Oh wow, you figured it out! That's pretty awesome. I also noted you fixed a
bunch of other problems as well. I'll pull your changes tonight and compile
a fresh copy of Dragon Basic. If I can't reproduce the issues anymore, I'll
comment the tickets as fixed and close them out. Also, if I can figure out
how your testing setup works I can probably contribute to adding more test
cases to your existing test suites (if you have any).

Cheers,

Alex,

**Comment by supercom32** [comment]
Regression issue found using the latest version of Dragon Basic under Linux.

Unfortunately this issue appears to only be partially fixed. While it does work with the simple test case provided with this change set, it doesn't work in other edge cases. In addition, it seems to cause a regression issue as String array compares seem to be broken now? The following is a simple test case reproducing the issues I'm seeing:

#title "TestCase"
#include <gba.dbc>

Dim sampleArray$(20)
Sub example
   sampleArray$[0] = "This line causes !currently_naked error."
   ;If sampleArray$[1] = "This line causes the error... example: unknown word compare at 6694"
   ;End If
End Sub

start:
   while
   loop

This code functionally does nothing, but is enough to cause MF to generate errors. Under this test case, MF will still complain about being "!currently_naked". In addition, if you comment that line out and un-comment the next two lines,  you will get an "unknown word compare" errors, which under the previous build never happened. 

Note: Attached to this comment is a copy of the file in question (in case you don't want to copy and paste the contents). For some reason white space and pasting code in comments doesn't work as well as I had expected.  ┐(´д｀)┌

[testcase.zip](https://github.com/uli/dragonbasic/files/1602317/testcase.zip)

**Comment by supercom32** [comment]
Hey Uli,

So I've been helping out and answering questions from this user "Ludo77".
It seems like I've satisfied his initial and follow up questions (Even
though they were unrelated to each other). However, now that it's resolved
he's stopped replying to the ticket.

I'm not sure how Github works to be honest, but is it possible to get
access so that I can close out his issue? Also if it's possible, maybe I
can help prioritize the backlog of items/issues so they are tagged with the
proper Labels, etc?

Cheers,

Alex,

**Comment by uli** [comment]
The bit with the failed assertion is the same as fixed previously for various operators, but for the MOVE word.

I doubt that the string comparison ever worked, because the "COMPARE" word it uses was simply not implemented. It is now. Sorry for the delay.
